### ISSUE TITLE
Feature request: support for OpenAI's Realtime API

### ISSUE THREAD

**Issue by AlexM4H** [matatonic/openedai-whisper#6]
See https://openai.com/index/introducing-the-realtime-api and https://platform.openai.com/docs/guides/realtime for more details.

**Comment by matatonic** [comment]
I'm looking into this, but my first though is that this will be a new project (whisper + tts), not an update to existing projects.

**Comment by AlexM4H** [comment]
You may be right...

**Comment by matatonic** [comment]
Also, that doing it in python is a pretty bad idea.

**Comment by AlexM4H** [comment]
I know what you mean. Maybe the new project will be in Rust?

**Comment by matatonic** [comment]
Could be, but for now, I'm going to close this, I don't expect to add real time APi to this repo. If anyone else is interested, feel free to leave a comment if there is something else to discuss around it.
